import vehicles from '@/data/vehicle-reference.json';
import reference from '@/data/reference.json';
import {runtime,database} from './server';import {AppError} from './reports.mjs';
const HEADERS:Record<string,string[]>={VTC_Vehicles:['id','urban_number','general_number','brand','model','source_date'],VTC_Submissions:['id','plate','category','status','publication','revision','note','details','created_at','updated_at','vehicle'],VTC_Evidence:['id','report_id','plate','kind','mime','size','metadata','evidence_link'],VTC_Audit:['id','report_id','revision','action','actor','payload','created_at'],VTC_Reference:['id','category','source_details','source_date']};
let cachedToken:{value:string;until:number}|null=null;
const b64=(x:Uint8Array)=>btoa(String.fromCharCode(...x)).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
async function accessToken(){if(cachedToken&&cachedToken.until>Date.now())return cachedToken.value;const raw=runtime().GOOGLE_SERVICE_ACCOUNT_JSON;if(!raw)throw new AppError('Google Sheets todavía no está conectado. Tus datos siguen guardados de forma privada.',503);const sa=JSON.parse(raw);const now=Math.floor(Date.now()/1000);const enc=new TextEncoder();const header=b64(enc.encode(JSON.stringify({alg:'RS256',typ:'JWT'})));const claim=b64(enc.encode(JSON.stringify({iss:sa.client_email,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600})));const keyBytes=Uint8Array.from(atob(sa.private_key.replace(/-----[^-]+-----|\s/g,'')),c=>c.charCodeAt(0));const key=await crypto.subtle.importKey('pkcs8',keyBytes,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const signature=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,enc.encode(header+'.'+claim));const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:header+'.'+claim+'.'+b64(new Uint8Array(signature))}),signal:AbortSignal.timeout(12000)});if(!r.ok)throw Object.assign(Error('Google authorization failed'),{status:r.status});const data=await r.json() as any;if(!data.access_token)throw Error('Missing access token');cachedToken={value:data.access_token,until:Date.now()+3300000};return cachedToken.value;}
export class GoogleSheets{ready=false;async request(path:string,body?:any,method?:string){const id=runtime().GOOGLE_SHEET_ID;if(!id)throw Error('Missing sheet');const r=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+encodeURIComponent(id)+path,{method:method??(body?'POST':'GET'),headers:{Authorization:'Bearer '+await accessToken(),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(12000)});if(!r.ok)throw Object.assign(Error('Google Sheets request failed'),{status:r.status});return r.json() as Promise<any>}
 async ensure(){if(this.ready)return;const info=await this.request('?fields=sheets.properties');for(const [tab,headers] of Object.entries(HEADERS)){const sheet=info.sheets?.find((s:any)=>s.properties.title===tab);if(!sheet)await this.request(':batchUpdate',{requests:[{addSheet:{properties:{title:tab,gridProperties:{rowCount:10000,columnCount:20}}}}]});const data=await this.request('/values/'+encodeURIComponent(tab+'!A1:T1'));const existing=data.values?.[0]??[];if(existing.length&&headers.some((x,i)=>existing[i]!==x))throw Object.assign(Error('Existing sheet headers conflict'),{status:409});if(!existing.length)await this.write(tab+'!A1',[headers]);}const mirrorId='vehicle-reference-v1';const db=database();const stored=await db.prepare('SELECT value FROM settings WHERE key=?').bind(mirrorId).first();if(!stored){const values=Object.entries(vehicles).map(([id,r])=>[id,...r,'2026-02-25']);const found=await this.request('/values/'+encodeURIComponent('VTC_Vehicles!A2:F'));if(found.values?.length&&JSON.stringify(found.values)!==JSON.stringify(values))throw Object.assign(Error('Vehicle tab differs'),{status:409});if(!found.values?.length)await this.write('VTC_Vehicles!A2',values);await db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').bind(mirrorId,'done').run();}this.ready=true;}
 async prepare(){await this.ensure();const db=database(),version=reference.sourceDate+":"+Object.keys(reference.records).length;const saved=await db.prepare('SELECT value FROM settings WHERE key=?').bind('reference-sheet-version').first<{value:string}>();if(saved?.value===version)return;const expected=Object.entries(reference.records).map(([id,r])=>[id,r.category,r.info,reference.sourceDate]);const existing=await this.request('/values/'+encodeURIComponent('VTC_Reference!A2:D'));const rows=existing.values??[];if(rows.length&&JSON.stringify(rows)!==JSON.stringify(expected))throw Object.assign(Error('Reference tab differs; owner reconciliation required'),{status:409});if(!rows.length)await this.write('VTC_Reference!A2',expected);await db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('reference-sheet-version',version).run();}

 async write(range:string,values:any[][]){return this.request('/values:batchUpdate',{valueInputOption:'RAW',data:[{range,values}]});}
 async upsert(tab:string,id:string,values:any[]){await this.ensure();if(!HEADERS[tab])throw Error('Unknown tab');const db=database(),mapId=tab+':'+id;let mapping=await db.prepare('SELECT row FROM sheet_rows WHERE id=?').bind(mapId).first<{row:number}>();if(!mapping){const cells=await this.request('/values/'+encodeURIComponent(tab+'!A:A'));const list=cells.values??[];const existing=list.findIndex((r:any)=>r[0]===id);const max=await db.prepare('SELECT max(row) AS n FROM sheet_rows WHERE tab=?').bind(tab).first<{n:number}>();const row=existing>=1?existing+1:Math.max(list.length+1,(max?.n??1)+1);await db.prepare('INSERT OR IGNORE INTO sheet_rows(id,tab,row) VALUES(?,?,?)').bind(mapId,tab,row).run();mapping=await db.prepare('SELECT row FROM sheet_rows WHERE id=?').bind(mapId).first<{row:number}>();}const row=mapping!.row;const current=await this.request('/values/'+encodeURIComponent(tab+'!A'+row));if(current.values?.[0]?.[0]&&current.values[0][0]!==id)throw Object.assign(Error('Sheet row moved; reconciliation required'),{status:409});const origin=runtime().PUBLIC_ORIGIN??'';if(!/^https:\/\//.test(origin))throw Object.assign(Error('Public origin not configured'),{status:409});const safe=values.map(v=>typeof v==='string'&&v.startsWith('/api/reports/')?origin+v:v);await this.write(tab+'!A'+row,[[id,...safe]]);}
}
